services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\BooxiClientBundle\:
        resource: '../src/*'
        exclude: '../../{Model}'

    IDCI\Bundle\BooxiClientBundle\Client\BooxiApiClient:
        arguments:
            $apiKey: '%idci_booxi_client.api_key%'
            $partnerKey: '%idci_booxi_client.partner_key%'